### ISSUE TITLE
Allow copying text from the output

### ISSUE THREAD

**Issue by patrickkwang** [maximusunc/AardwolfMUDClient#11]

**Comment by maximusunc** [comment]
This should be simple, but we should give it a little extra thought. Right now, you can't copy output text because the input bar always keeps its focus so you can't click away. If that's not what we want, then I can just move that feature and you'll be able to highlight and copy any of the text on the page. The input focus might have been a terminal thing where we didn't want it to lose focus, but a webpage is different. Why do you want to be able to copy output text?

**Comment by patrickkwang** [comment]
Instead of preventing a change of focus, could we just catch all keystrokes everywhere and direct them to the input?

**Comment by maximusunc** [comment]
I've looked into this a little bit. It's definitely doable to attach a keypress listener to the entire DOM, but that keypress listener is going to catch ALL keypresses and we'd have to parse out any non-input input. At this point, I can remove the onblur so you can click away from the input, cause you can always refocus it later.

**Comment by maximusunc** [comment]
I took out the onblur in 4895700054d98dc4408a32957fe2ece6453ac6ba. This will also help when we have buttons we want to click. I can leave this open if you want to tackle a global input listener.
